# Generated by Django 3.1.3 on 2021-04-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_product_catogery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catogery',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.catogery'),
            preserve_default=False,
        ),
    ]
