# Generated by Django 3.1.3 on 2021-06-13 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210612_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catogery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.catogery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
